---
output:
  word_document: default
  html_document: default
---
Liang Hu

This work builds 3 classification models to predict credit risk.

```{r}
#load libraries
library(caret)
library(RWeka)
library(e1071)
```

```{r}
#read data
setwd(getwd())
credit <- read.csv("credit-g.csv")
```

```{r}
#create training set and test set
set.seed(1991)
trainIndex <- createDataPartition(credit$class, p=0.67, list=F, times=1)
creditTrain <- credit[trainIndex, ]
creditTest <- credit[-trainIndex, ]
```

```{r}
#decision trees, independent test set
model <- J48(class~., data=creditTrain)
prediction <- predict(model, creditTest)
CM <- confusionMatrix(prediction, creditTest$class)
CM
print(paste0("The estimated true error is ", 1-round(CM$overall[1], 3)))
```

```{r}
#decision trees, cross validation (10 folds)
ctrl1 <- trainControl(method="cv", savePred=T, classProb=T, number=10)
#tune parameters
set.seed(1991)
treeGrid <- expand.grid(C=(1:6)*0.05, M=(1:5))
model1 <- train(class~., data=credit, method="J48", trControl=ctrl1,
               tuneGrid=treeGrid)
model1
plot(model1)
print("The estimated true error is 0.284.")
print("The selected parameters are C=0.15 and M=1.")
```

```{r}
#decision trees, cross validation (7 folds)
ctrl2 <- trainControl(method="cv", savePred=T, classProb=T, number=7)
#tune parameters
set.seed(1991)
treeGrid <- expand.grid(C=(1:6)*0.05, M=(1:5))
model2 <- train(class~., data=credit, method="J48", trControl=ctrl2,
               tuneGrid=treeGrid)
model2
plot(model2)
print("The estimated true error is 0.271.")
print("The selected parameters are C=0.10 and M=1.")
```

```{r}
#decision trees, cross validation (5 folds)
ctrl3 <- trainControl(method="cv", savePred=T, classProb=T, number=5)
#tune parameters
set.seed(1991)
treeGrid <- expand.grid(C=(1:6)*0.05, M=(1:5))
model3 <- train(class~., data=credit, method="J48", trControl=ctrl3,
               tuneGrid=treeGrid)
model3
plot(model3)
print("The estimated true error is 0.283.")
print("The selected parameters are C=0.10 and M=4.")
```

```{r}
#naive Bayes, independent test set
model <- naiveBayes(class~., data=creditTrain)
prediction <- predict(model, creditTest)
CM <- confusionMatrix(prediction, creditTest$class)
CM
print(paste0("The estimated true error is ", 1-round(CM$overall[1], 3)))
```

```{r}
#naive Bayes, cross validation (10 folds)
ctrl1 <- trainControl(method="cv", savePred=T, classProb=T, number=10)
set.seed(1991)
model1 <- train(class~., data=credit, method="nb", trControl=ctrl1)
model1
print("The estimated true error is 0.3.")
```

```{r}
#naive Bayes, cross validation (7 folds)
ctrl2 <- trainControl(method="cv", savePred=T, classProb=T, number=7)
set.seed(1991)
model2 <- train(class~., data=credit, method="nb", trControl=ctrl2)
model2
print("The estimated true error is 0.3.")
```

```{r}
#naive Bayes, cross validation (5 folds)
ctrl3 <- trainControl(method="cv", savePred=T, classProb=T, number=5)
set.seed(1991)
model3 <- train(class~., data=credit, method="nb", trControl=ctrl3)
model3
print("The estimated true error is 0.3.")
```

```{r}
#kNN, independent test set
#tune the parameter k
train_error <- c()
test_error <- c()
for(i in 1:100) {
  model <- knn3(class~., data=creditTrain, k=i)
  prediction_test <- predict(model, creditTest, type="class")
  test_error[i] <- 1-confusionMatrix(prediction_test, creditTest$class)$overall[1]
  prediction_train <- predict(model, creditTrain, type="class")
  train_error[i] <- 1-confusionMatrix(prediction_train, creditTrain$class)$overall[1]
}
plot(c(1, 100), c(0, 0.5), type='n', xlab='k', ylab='error')
lines(test_error, col='red')
lines(train_error, col='blue')
legend(70, 0.45, c('training error', 'testing error'), 
       lty=c(1,1), lwd=c(2.5,2.5), col=c('blue', 'red'))
```

```{r}
#try k=20
model <- knn3(class~., data=creditTrain, k=20)
prediction <- predict(model, creditTest, type="class")
CM <- confusionMatrix(prediction, creditTest$class)
CM
print(paste0("The estimated true error is ", 1-round(CM$overall[1], 3)))
```

94 "bad" in 99 "bad" are predicted as "good". This obviously increases the bank's credit risk.

```{r}
#kNN, cross validation (10 folds)
set.seed(1991)
model1 <- train(class~., data=credit, method="knn", trControl=ctrl1,
               tuneGrid=expand.grid(k=c(1:100)))
model1
print("The estimated true error is 0.288.")
print("The selected parameters are k=69.")
```

```{r}
#kNN, cross validation (7 folds)
set.seed(1991)
model2 <- train(class~., data=credit, method="knn", trControl=ctrl2,
               tuneGrid=expand.grid(k=c(1:100)))
model2
print("The estimated true error is 0.288.")
print("The selected parameters are k=64.")
```

```{r}
#kNN, cross validation (5 folds)
set.seed(1991)
model3 <- train(class~., data=credit, method="knn", trControl=ctrl3,
               tuneGrid=expand.grid(k=c(1:100)))
model3
print("The estimated true error is 0.287.")
print("The selected parameters are k=64.")
```





